Updated to assemble with ATasm located at : https://github.com/CycoPH/atasm Had to modify assembler line 2077 of asm.c, comment said "was 2? probably a typo", reviewed older version of assembler and this seems correct and got past this error.
nightraider.asm is the main file, all other files come from this and will need to be maintained together if this is desired, any changes to nightraider.asm need to also be made to the appropriate separate file.

Currently this problem is occuring:
DE:14  CA                  DEX
DF:14  D0 F7               BNE ?6
E1:14  A2 03               LDX #$03
E3:14  B5 A
In nightraider.asm, line 1767--
 Error: Invalid compiler directive in expression.
7    ?14        LDA HIT1,X
E5:14  29 08               AND #$08
E7:14  95 A7               STA HIT1,X